# Generated by Django 6.0.3 on 2026-03-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('pinned', models.BooleanField(default=False)),
            ],
        ),
    ]
