# Generated by Django 6.0.3 on 2026-03-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
            ],
        ),
    ]
