# Generated by Django 4.2.10 on 2024-04-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('exp_date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
