# Generated by Django 4.2.10 on 2024-04-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='exp_date',
            new_name='expiry',
        ),
    ]
