# Generated by Django 5.1.5 on 2025-01-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mark', models.IntegerField()),
                ('colllege', models.CharField(max_length=300)),
            ],
        ),
    ]
