# Generated by Django 5.1.5 on 2025-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_student1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demotable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
